version: '2'

services:

  php5.6-apache.dev:
    image: yousan/php5.6-apache:0.6
    ports:
      - 80:80
    volumes:
      - ~/public_html:/var/www/vhosts
    environment:
       PMA_HOST: mysql
       PMA_USER: root
       PMA_PASSWORD: example
#      WORDPRESS_DB_PASSWORD: example
#    links:
#      - links

  mysql.dev:
    image: mariadb
    environment:
      MYSQL_ROOT_PASSWORD: example
      MYSQL_USER: yousan
      MYSQL_PASSWORD: example
    ports:
      - 3306:3306
#    links:
#      - db

  dnsmasq.dev:
    image: yousan/dnsmasq:0.6
    ports:
      - 53:53/tcp
      - 53:53/udp
    cap_add:
      - NET_ADMIN
